apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: webfrontend
  name: webfrontend
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 0
  - name: https
    port: 8443
    targetPort: 0
  selector:
    app: webfrontend
  type: ClusterIP