 apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app: webfrontend
  name: webfrontend
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: webfrontend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations: {}
      labels:
        app: webfrontend
    spec:
      containers:
      - args: []
        envFrom:
        - configMapRef:
            name: webfrontend
        - secretRef:
            name: webfrontend
        image: '{{ .Values.images.webfrontend }}'
        imagePullPolicy: Always
        name: webfrontend
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8443d:

          name: https
      terminationGracePeriodSeconds: 180